### ISSUE TITLE
Notebook doesn't work out of the box

### ISSUE THREAD

**Issue by stephantul** [mikekestemont/spl2018scribes#1]
All the filepaths in the notebook assume the notebook is run from a subfolder of the main folder (i.e. all the paths are prefaced with `../`). 

This is not the case when the repository is cloned, which results in `FileNotFoundError`s in multiple cells.

**Comment by mikekestemont** [comment]
Sorry, couldn't finish this before the weekend. Should be fixed now! Thanks for catching this though.
